category/urls.py
from django.urls import path
from category import views

app_name = 'category'

urlpatterns = [
    path('category/<slug:category_name_slug>/', views.category, name='category'),
    path('categories/', views.category_select, name='categories'),
    path('page/<slug:page_name_slug>/', views.page, name='page'),
    path('submitComment/', views.submitComment, name='submitComment')
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),

]

myaccount/urls.py
from django.urls import path
from myaccount import views


app_name = 'myaccount'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.myaccount, name='myaccount'),
    path('changepwd/', views.changepwd, name='changepwd'),
]

wonderland/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


from home import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),
    path('search/', include('search.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('home/', include('home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone

from myaccount.models import UserProfile


class Category(models.Model):
    NAME_MAX_LENGTH = 128
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    def __set__(self):
        return self.name
class Page(models.Model):
    CHAR_MAX_LENGTH = 128
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=CHAR_MAX_LENGTH, unique=True)
    rate = models.CharField(max_length=20, default="10")
    intro = models.CharField(max_length=CHAR_MAX_LENGTH)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Page, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    wonder = models.ForeignKey(Page, on_delete=models.CASCADE)
    rate = models.CharField(max_length=20, default="0")
    comment = models.CharField(max_length=512)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.user.user.username

category/views.py
from django.contrib.auth.models import User
from django.db.models import Avg
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from category.models import Category, Page, Comment

# Create your views here.
from myaccount.models import UserProfile


def category(request, category_name_slug):
    context_dict = {}
    if category_name_slug == 'all':
        all_dict = {}
        all_dict['name'] = "ALL "
        pages = Page.objects.all()
        context_dict['pages'] = pages
        for page in pages:
            page.img = 'images/places/' + page.slug + '.jpg'
        context_dict['category'] = all_dict
        context_dict['bkg'] = 'images/continent/all.jpg'
        return render(request, 'category/category.html', context=context_dict)
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages

        for page in pages:
            page.img = 'images/places/' + page.slug + '.jpg'

        context_dict['category'] = category
        context_dict['bkg'] = 'images/continent/' + category.slug + '.jpg'
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    return render(request, 'category/category.html', context=context_dict)


def category_select(request):
    return render(request, 'category/category_select.html')


def page(request, page_name_slug):
    context_dict = {}
    try:
        page = Page.objects.get(slug=page_name_slug)
        context_dict['page'] = page
        context_dict['bkg'] = "images/places/" + page.slug + ".jpg"
        if not request.user.username == "":
            user_profile = UserProfile.objects.get(user=request.user)
            user_rate = Comment.objects.filter(user=user_profile, wonder=page)
            if user_rate.count() > 0:
                context_dict['rate'] = user_rate[0].rate
            else:
                context_dict['rate'] = "no"
        else:
            context_dict['rate'] = "anonymouse"

        context_dict['comments'] = Comment.objects.filter(wonder=page)

    except Page.DoesNotExist:
        context_dict['page'] = None
    return render(request, 'category/page.html', context=context_dict)


@ensure_csrf_cookie
def submitComment(request):
    if request.method == "POST":
        print(request.POST)
        user_name = request.POST['userName']
        user_comment = request.POST['userComment']
        user_rate = request.POST['userRate']
        user_wonder = request.POST['userWonder']

        user = User.objects.get(username=user_name)
        wonder = Page.objects.get(name=user_wonder)
        user_profile = UserProfile.objects.get(user=user)

        comment = Comment.objects.filter(user=user_profile, wonder=wonder)
        if comment.count() == 0:
            comment = Comment()
            comment.user = user_profile
            comment.rate = user_rate
            comment.comment = user_comment
            comment.wonder = wonder
            comment.save()
        else:
            comment = Comment.objects.filter(user=user_profile, wonder=wonder)[0]
            comment.rate = user_rate
            comment.comment = user_comment
            comment.save()

        # update page's rate
        ave_rate = Comment.objects.filter(wonder=wonder).aggregate(Avg('rate'))
        print(ave_rate)
        wonder.rate = ave_rate['rate__avg']
        wonder.save()

        return HttpResponse(-1)

templates/category/base.html
<!DOCTYPE>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="utf-8" />
        <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{#        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block title_block %}
        {% endblock %}
    </head>
    <body>
    <style>
        *{
            font-family:'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif
        }
    </style>
    {% block body_block %}
    {% endblock %}
    </body>
</html>

templates/category/category.html
{% extends 'category/base.html' %}
{% load staticfiles %}

{% block title_block %}
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <title>{{ category }}</title>
{% endblock %}

{% block body_block%}
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
      <div class="container">
        <a class="navbar-brand text-white" href="{% url 'home:index' %}" style="font-family: 'Trade Winds'">WONDERLAND</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto pt-4">
                {% if user.is_authenticated %}
                  <a id="user" class="btn btn-outline-light mr-2" href="{% url 'myaccount:logout' %}">{{ user.username }}</a>
                {% else %}
                  <a class="btn btn-outline-light mr-2" href="{% url 'myaccount:signup' %}">Sign up</a>
                  <a class="btn btn-outline-light" href="{% url 'myaccount:login' %}">Login</a>
                {% endif %}
            </ul>
        </div>
      </div>
    </nav>
    <header class="continent" style="background-image: url({% static bkg %}); position: relative;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading text-center">
                        <h1 style="font-family: 'Trade Winds'">{{category.name}}</h1>
                        <span class="subheading"> Exploring and Travelling the BEST of {{ category.name }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="row row-cols-1 row-cols-md-3 wonder-result center-block">
{#    every wonder#}
        {% for page in pages %}
            <div class="col mb-4">
                <a href="{% url 'category:page' page.slug %}" class="card wonder-card shadow-lg rounded">
                    <div class="img-box" style="background-image: url({% static page.img %})"></div>
                    <div class="card-body">
                        <span style="font-family: 'Trade Winds'; font-size: 1.5rem;">{{page.name}}</span>
                        <span class="ml-2" style="font-family: 'Trade Winds'">{{ page.rate }}</span>
                        <p style="font-size: 0.8rem;">{{ page.intro }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="text-center mb-3">
        <span class="text-center">-nothing more for now-</span>
    </div>
{% endblock %}

templates/category/category_select.html
{% extends 'category/base.html' %}
{% load staticfiles %}

{% block title_block %}
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <title>Select a Category</title>
{% endblock %}

{% block body_block %}

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-5 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal" style="font-family: 'Trade Winds';">WONDERLAND</h5>
    {% if user.is_authenticated %}
        <a id="user" class="btn btn-outline-dark mr-2" href="{% url 'myaccount:logout' %}">{{ user.username }}</a>
    {% else %}
        <a class="btn btn-outline-dark mr-2" href="{% url 'myaccount:signup' %}">Sign up</a>
        <a class="btn btn-outline-dark" href="{% url 'myaccount:login' %}">Login</a>
    {% endif %}
    </div>
    <div class="container">
        <div class="d-flex flex-row justify-content-center p-4">
            <h1 class="text-center" style="font-family: 'Trade Winds';">Categories</h1>
        </div>
        <div class="d-flex flex-column justify-content-center">
            <h2>BY CONTINENT</h2>
            <div class="d-flex flex-column align-items-center p-4 px-md-5">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'europe' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/europe.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">EUROPE</h5>
                            </div>
                        </a>
                    </div>
                {#  item2  #}
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'asia' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/asia.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">ASIA</h5>
                            </div>
                        </a>
                    </div>
                {#  item3#}
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'africa' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/africa.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">AFRICA</h5>
                            </div>
                        </a>
                    </div>
{#                    item4#}
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'south-america' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/south-america.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">SOUTH AMERICA</h5>
                            </div>
                        </a>
                    </div>
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'north-america' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/north-america.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">NORTH AMERICA</h5>
                            </div>
                        </a>
                    </div>
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'oceania' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/oceania.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">OCEANIA</h5>
                            </div>
                        </a>
                    </div>
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'antarctica' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/antarctica.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">ANTARCTICA</h5>
                            </div>
                        </a>
                    </div>
                    <div class="col mb-4 continent-card">
                        <a href="{% url 'category:category' 'all' %}" class="card  shadow-lg">
                            <img src="{% static 'images/continent/all.jpg' %}" class="card-img-top" alt="...">
                            <div class="overlay d-flex flex-column justify-content-center text-center">
                                <h5 class="card-title text-white" style="font-family: 'Trade Winds';">ALL</h5>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/category/page.html
{% extends 'category/base.html' %}
{% load staticfiles %}

{% block title_block %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <title>{{ category }}</title>
{% endblock %}

{% block body_block%}
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
      <div class="container">
        <a class="navbar-brand text-white" href="{% url 'home:index' %}" style="font-family: 'Trade Winds'">WONDERLAND</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto pt-4">
                {% if user.is_authenticated %}
                  <a id="user" class="btn btn-outline-light mr-2" href="{% url 'myaccount:myaccount' %}">{{ user.username }}</a>
                {% else %}
                  <a class="btn btn-outline-light mr-2" href="{% url 'myaccount:signup' %}">Sign up</a>
                  <a class="btn btn-outline-light" href="{% url 'myaccount:login' %}">Login</a>
                {% endif %} 
            </ul>
        </div>
      </div>
    </nav>
    <header class="continent" style="background-image: url({% static bkg %}); background-position: center; position: relative;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading text-center">
                        <h1 id="wonder" style="font-family: 'Trade Winds'">{{page.name}}</h1>
                        <span class="subheading" style="font-size: 1rem">Average Rate</span>
                        <span class="subheading" style="font-family: 'Trade Winds'">{{ page.rate }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="page-content rounded p-4 text-justify shadow">
            <div>
                <span></span>
                <p>{{ page.intro }}</p>
            </div>
        </div>
        <div class="mt-4 text-center">
            <span>The Location</span>
            <div class="shadow rounded mt-3" id="map"></div>
        </div>
        <div class="rate mt-5 mb-5">
            {% if not user.is_authenticated %}
            <span class="d-block mb-5 text-center">Login First to Give Your Rate and Comment ! </span>
            {% elif rate == "no" %}
            <span class="d-block mb-5 text-center">Give Your Rate Here! </span>
            {% else %}
            <span class="d-block mb-5 text-center">You have rate the wonder as {{ rate }} ! </span>
            {% endif %}
            {% if user.is_authenticated %}
            <div id="rate-box" data-rate={{ rate }} class="mt-2">
                <select id="rating">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                </select>
            </div>
            {% endif %}
        </div>
        <div>
            <span class="d-block text-center mt-3">Here are some Comments from Other Travellers!</span>
            <div class="px-5 pb-5">
                {% for comment in comments %}
                <div class="comment shadow rounded px-4 pt-3 pb-1 mt-3 border-bottom border-left border-right border-top">
                    <div class="commenter d-flex flex-row">
                        {% if comment.user.picture == "" %}
                        <img class="rounded-circle" src="{% static 'images/avatar.png' %}">
                        {% else %}
                        <img class="rounded-circle" src="{{ MEDIA_URL }}{{ comment.user.picture }}">
                        {% endif %}
                        <div class="d-flex flex-column ml-3">
                            <span>{{ comment.user.user.username}}</span>
                            <span>{{ comment.date }}</span>
                        </div>
                        <div class="d-flex flex-column ml-auto">
                            <span style="font-family: 'Trade Winds';font-size: 0.5rem;;">Commentor's rate</span>
                            <span class="text-right" style="font-family: 'Trade Winds';font-size: 1.5rem;color: #D55754;">{{ comment.rate }}</span>
                        </div>
                    </div>
                    <p class="comment-text mt-1 text-justify">
                        {{ comment.comment }}
                    </p>
                </div>
                {% endfor %}

            {#    end for#}
            </div>
            <div class="placeholder"></div>
        </div>
    </div>
{#    bottom input #}
    {% if  user.is_authenticated %}
    <div class="fixed-bottom comment-box container">
        <div class="comment-btn text-center mb-3">
            <div class="comment-btn-bkg mx-auto">
                <i style="color: white" class="fa fa-pencil"></i>
            </div>
        </div>
        <div class="input-group mb-3">
          <input id="commentBox" type="text" class="form-control" placeholder="Leave your comment here!" aria-label="Recipient's username" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button id="submitComment" class="btn btn-outline-secondary" type="button">
            <i class="fa fa-check"></i></button>
          </div>
        </div>
    </div>
    {% endif %}


    <script src="{% static 'jquery.barrating.min.js' %}"></script>
    <script src="{% static 'page.js' %}"></script>

    <script>
    // Initialize and add the map

        function initMap() {
          // The location of Stonehenge
            var uluru = {lat: 51.178969, lng: -1.826215};
          // The map, centered at Stonehenge
            var location = 0;
            var geocoder = new google.maps.Geocoder();
            var map = new google.maps.Map(
                document.getElementById('map'), {zoom: 13});
            geocoder.geocode({'address':'{{ page.name }}'},function (results, status) {
                location = results[0].geometry.location;
                map.setCenter(location);
            });
          {#var marker = new google.maps.Marker({position: uluru, map: map});#}
        }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBnDoxjCZgNymxhz0-pTTnX3Cuq7c1Jq-U&callback=initMap">
    </script>

{% endblock %}