category/urls.py
from django.urls import path
from category import views

app_name = 'category'

urlpatterns = [
    path('category/<slug:category_name_slug>/', views.category, name='category'),
    path('categories/', views.category_select, name='categories'),
    path('page/<slug:page_name_slug>/', views.page, name='page'),
    path('submitComment/', views.submitComment, name='submitComment')
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),

]

myaccount/urls.py
from django.urls import path
from myaccount import views


app_name = 'myaccount'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.myaccount, name='myaccount'),
    path('changepwd/', views.changepwd, name='changepwd'),
]

wonderland/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


from home import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),
    path('search/', include('search.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('home/', include('home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myaccount/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# UserProfile, model for website users


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional attributes
    logInDate = models.DateField(null=True)
    personalURL = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

myaccount/forms.py
from django.contrib.auth.models import User
from myaccount.models import UserProfile
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('personalURL', 'picture',)

myaccount/views.py
from django.shortcuts import render
from myaccount.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from myaccount.models import UserProfile
from django.utils import timezone
from category.models import Comment, Page



# Create your views here.
# Register to be a user

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,
                  'myaccount/signup.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})

# Login for users
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                profile = UserProfile.objects.get(user=user)
                lastLogin = profile.logInDate
                currentLogin = timezone.now()
                profile.logInDate = currentLogin
                profile.save()
                qs1 = Comment.objects.filter(user=profile).order_by('date')[:3]
                qs2 = Comment.objects.filter(user=profile).order_by('rate')[:5]
                pages = {}
                for item in qs2:
                    wonder_name = item.wonder
                    page = Page.objects.get(name=wonder_name)
                    pages[wonder_name] = page
                return render(request, 'myaccount/myaccount.html', context={'profile': profile, 'lastLogin': lastLogin, 'qs1': qs1, 'pages':pages})
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'myaccount/login.html')


@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")

# Logout for users
@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('myaccount:login'))

@login_required
def myaccount(request):
    user = request.user
    profile = UserProfile.objects.get(user=user)
    lastLogin = profile.logInDate
    currentLogin = timezone.now()
    profile.logInDate = currentLogin
    profile.save()
    qs1 = Comment.objects.filter(user=profile).order_by('-date')[:3]
    qs2 = Comment.objects.filter(user=profile).order_by('-rate')[:5]
    pages = {}
    for item in qs2:
        wonder_name = item.wonder
        page = Page.objects.get(name=wonder_name)
        pages[wonder_name] = page
    return render(request, 'myaccount/myaccount.html', context={'profile': profile, 'lastLogin': lastLogin, 'qs1': qs1, 'pages':pages})

@login_required
def changepwd(request):
    if request.method == 'POST':
        user = request.user
        oldpassword = request.POST.get('oldpassword')
        newpassword = request.POST.get('newpassword')
        newpassword1 = request.POST.get('newpassword1')
        if newpassword != oldpassword:
            if newpassword == newpassword1:
                user.set_password(newpassword)
                user.save()
                return render(request, 'myaccount/login.html')
            else:
                return HttpResponse("Different passwords, check again!")
        else:
                return HttpResponse("New password must differ from the old!")
    else:
        return render(request, 'myaccount/changepwd.html')

templates/myaccount/base.html
<!DOCTYPE>
{% load staticfiles %}

<html>
    <head>
        <title>
            {% block title_block %}
            {% endblock %}
        </title>
        <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    </head>
    <body style="background-image:url(/static/images/myaccount/base_background.jpg);background-size: cover">
    <div class="text-right mt-3 mr-4">
        <a class="navbar-brand text-white " href="{% url 'home:index' %}" style="font-family: 'Trade Winds'">WONDERLAND</a>
        {% if user.is_authenticated %}
        <div style="display:inline">
            <a href="{% url 'myaccount:logout' %}"><button class="btn btn-light">Logout</button></a>
        </div>
        <div style="display:inline">
            <a href="{% url 'myaccount:myaccount' %}"><button class="btn btn-light">Myaccount</button></a>
        </div>
        {% else %}
        <div style="display:inline">
            <a href="{% url 'myaccount:signup' %}"><button class="btn btn-light">Sign Up</button></a>
        </div>
        <div style="display:inline">
            <a href="{% url 'myaccount:login' %}"><button class="btn btn-light">Login</button></a>
        </div>
        {% endif %}
    </div>

    <div class="d-flex flex-column align-items-center pt-5 pb-5 mt-5 rounded shadow-lg" style="width:60%;margin: auto;background-color: rgba(255,255,255,0.9)">
        {% block body_block %}
        {% endblock %}
    </div>

    </body>
</html>

templates/myaccount/changepwd.html
{% extends 'myaccount/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Change Password
{% endblock %}

{% block body_block %}
<div class="mb-5">
    <h1 style="margin-top:30px; font-family: 'Trade Winds'">Change Your Password</h1>
</div>
<div>
    <form id="changepwd_form" method="post" action="{% url 'myaccount:changepwd' %}">
        {% csrf_token %}
        Oldpassword: <input class="form-control" type="password" name="oldpassword" style="background-color: Transparent;"/>
        <br>
        New password: <input class="form-control" type="password" name="newpassword" style="background-color: Transparent;"/>
        <br>
        Check new password: <input class="form-control" type="password" name="newpassword1" style="background-color: Transparent;"/>
        <br>
        <div class="mx-auto text-center mt-3">
            <input type="submit" value="submit" class="btn btn-primary"/>
        </div>
    </form>
</div>

{% endblock %}

templates/myaccount/login.html
{% extends 'myaccount/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<div class="mb-5">
    <h1 style="font-family: 'Trade Winds'">Find Yourself in Wonderland</h1>
</div>
<div >
    <div>
        <form id="login_form" method="post" action="{% url 'myaccount:login' %}">
            <div class="form-group">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input class="form-control" id="username" type="text" name="username" value="" size="50" style="background-color: Transparent"/>
                <br />
                <label for="password">Password:</label>
                 <input class="form-control" id="password" type="password" name="password" value="" size="50" style="background-color: Transparent"/>
                <br />
                <div class="mx-auto text-center mt-3">
                    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
                </div>
            </div>
        </form>
    </div>

</div>

{% endblock %}

templates/myaccount/myaccount.html
<!DOCTYPE>
{% load staticfiles %}

<html>
    <head>
        <title>Myaccount</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>

    <body>
        <div style="height:7%">
            <div style="display:inline">
                <a href="{% url 'home:index' %}" style="margin-left:50px"><button style="background-color:Transparent; border:none; width:100px; height:50px;font-size:20px; font-weight:bold">HOME</button></a>
                <a href="{% url 'home:about' %}"><button style="background-color:Transparent; border:none; width:100px; height:50px;font-size:20px; font-weight:bold">ABOUT</button></a>
                <a href="{% url 'home:faq' %}"><button style="background-color:Transparent; border:none; width:100px; height:50px;font-size:20px; font-weight:bold">Q&A</button></a>
            </div>

            <div style="float:right; margin-right: 50px">
                Welcome! <font style="font-style:italic; font-weight:bold">{{ profile.user.username }}</font>
                <a href="{% url 'myaccount:logout' %}"><button style="background-color:Transparent; border:none; width:100px; height:50px;font-size:20px; font-weight:bold">Logout</button></a>
            </div>
        </div>

        <div class="mt-3 d-flex flex-row" style=" width:100%; height:93%">
            <div style="margin-left: 60px; width:20%; display:table-cell; text-align: center;">
                <div style="margin-top: 80px; display:inline-block;">
                    {% if profile.picture %}
                        <img src="{{ MEDIA_URL }}{{ profile.picture }}" alt="avatar" height="100" width="100">
                    {% else %}
                        <img src="{% static 'myaccount/default_avatar.jpg' %}" alt="avatar" height="100" width="100">
                    {% endif %}
                </div><br>

                <div style="margin-top: 10px; display:inline-block;">
                    Last login:
                    {% if lastLogin %}
                        {{ lastLogin }}
                    {% else %}
                        It is your first time to login!
                    {% endif %}
                </div><br>

                <div style="margin-top: 10px; display:inline-block;">
                    Username: {{ profile.user.username }}
                </div><br>

                <div style="margin-top: 10px; display:inline-block;">
                    {% if profile.user.email %}
                    Email:
                        <a href="{{ profile.user.email }}">{{ profile.user.email }}</a>
                    {% else %}
                    {% endif %}
                </div><br>

                <div style="margin-top: 10px; display:inline-block;">
                    {% if profile.personalURL %}
                        <a href="{{ profile.personalURL }}">Personal Website</a>
                    {% else %}
                    {% endif %}
                </div><br>

                <div style="margin-top: 10px; display:inline-block;">
                    <a href="{% url 'myaccount:changepwd' %}"><button>Change Password</button></a>
                </div>
            </div>

            <div style="width:80%; display:table-cell">
                <div style="margin-left:150px">
                    <font style="font-weight:bold">Favorites Wonders:</font>
                    <div style="margin-top: 10px">
                        {% if pages %}
                        {% for page in pages %}
                            {% with 'images/places/'|add:page.slug|add:'.jpg' as image_static %}
                            <a href="{% url 'category:page' page.slug %}" style="display:inline">
                                <img src="{% static image_static %}" alt="{{ page.name }}" height="150" width="150">
                            </a>
                            {% endwith %}
                        {% endfor %}
                        {% else %}
                        <div>
                            Let's find some interesting wonders!
                        </div>
                        {% endif %}
                    </div>
                </div><br>

                <div style="margin-top:10px; margin-left:150px">
                    <font style="font-weight:bold">Recent Comments:</font>
                    <div style="margin-top: 5px">
                        {% if qs1 %}
                        {% for item in qs1 %}
                        <div class="rounded shadow p-3" style="width: 90%;">
                            Wonder: {{ item.wonder }}<br>
                            Date: {{ item.date }}<br>
                            Comment: {{ item.comment }}
                        </div><br>
                        {% endfor %}
                        {% else %}
                        <div>
                            Seems you don't like sharing opinions...
                        </div>
                        {% endif %}
                    </div>
                </div><br>
            </div>
        </div>
    </body>
</html>

templates/myaccount/signup.html
{% extends 'myaccount/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Sign up
{% endblock %}

{% block body_block %}
<div>
    <h1 style="font-family: 'Trade Winds'">Begin Your Journey</h1>
</div>
{% if registered %}
<div>
    <strong>thank you for registering!</strong>
</div>
{% else %}
<div>
    <strong>register here!</strong><br />
</div>
<div>
    <form class="form-group" id="user_form" method="post" action="{% url 'myaccount:signup' %}"
      enctype="multipart/form-data" >

        {% csrf_token %}
        <div class="fieldWrapper">
            <label for="{{ user_form.subject.id_for_username }}">Username:</label>
            <input class="form-control" id="{{ user_form.subject.id_for_username }}" type="text" name="username" maxlength="150" required style="background-color: Transparent;"/>
            <font style="color:red">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</font>
        </div>
        <div class="fieldWrapper">
            <label for="{{ user_form.subject.id_for_email }}">Email address:</label>
            <input class="form-control" id="{{ user_form.subject.id_for_email }}" type="text" name="email" style="background-color: Transparent;"/>
            <font style="color:red">Not required.</font>
        </div>
        <div class="fieldWrapper">
            <label for="{{ user_form.subject.id_for_password }}">Password:</label>
            <input class="form-control" id="{{ user_form.subject.id_for_password }}" type="password" name="password" style="background-color: Transparent;" />
            <font style="color:red">Required.</font>
        </div>
        <div class="fieldWrapper">
            <label for="{{ profile_form.subject.id_for_personalURL }}">PersonalURL:</label>
            <input class="form-control" id="{{ profile_form.subject.id_for_personalURL }}" type="text" name="personalURL" style="background-color: Transparent;" />
            <font style="color:red">Not required.</font>
        </div>
        <div class="fieldWrapper">
            <label for="{{ profile_form.subject.id_for_picture }}">Picture:</label>
            <input class="form-control" type="file" name="picture" accept="image/*" id="{{ profile_form.subject.id_for_picture }}" style="background-color: Transparent;" >
            <font style="color:red">Not required.</font>
        </div>
        <div class="mx-auto text-center mt-3">
            <button class="btn btn-primary" type="submit" name="submit" value="Begin">Begin</button>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}