category/urls.py
from django.urls import path
from category import views

app_name = 'category'

urlpatterns = [
    path('category/<slug:category_name_slug>/', views.category, name='category'),
    path('categories/', views.category_select, name='categories'),
    path('page/<slug:page_name_slug>/', views.page, name='page'),
    path('submitComment/', views.submitComment, name='submitComment')
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),

]

myaccount/urls.py
from django.urls import path
from myaccount import views


app_name = 'myaccount'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.myaccount, name='myaccount'),
    path('changepwd/', views.changepwd, name='changepwd'),
]

search/urls.py
from django.urls import path
from search import views

app_name = 'search'

urlpatterns = [
    path('thebestwonders/', views.theBestWonders, name='thebestwonders'),
    path('searchpage/<str:typestring>/', views.searchResult, name='searchpage'),
    path('searchpage/', views.searchHome, name = 'searchhome')
]

wonderland/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


from home import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),
    path('search/', include('search.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('home/', include('home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/views.py
from django.shortcuts import render
from category.models import Page
from category.models import Category
# Create your views here.
def theBestWonders(request):
    page_list = Page.objects.order_by('-rate')[:6]
    context_dict = {}
    context_dict['pages'] = page_list
    return render(request, 'search/thebestwonders.html', context=context_dict)

def searchResult(request, typestring):
    context_dict = {}
    context_dict['isStr'] = True
    context_dict['keyword'] = "\'"+typestring+"\'"
    categories = Category.objects.all()
    for category in categories:
        if typestring.lower() == category.name.lower():
            context_dict['results'] = Page.objects.filter(category=category).order_by('-rate')
            return render(request, 'search/searchpage.html', context=context_dict)
    pages = Page.objects.all()
    for page in pages:
        if typestring.lower().replace(" ","") == page.name.lower().replace(" ",""):
            context_dict['results'] = Page.objects.filter(name=page.name).order_by("-rate")
            return render(request, 'search/searchpage.html', context=context_dict)

    context_dict['results'] = None
    return render(request, 'search/searchpage.html', context=context_dict)

def searchHome(request):
    context_dict = {}
    context_dict['isStr'] = False
    return render(request, 'search/searchpage.html', context=context_dict)

templates/search/base.html
<!DOCTYPE>
{% load staticfiles %}

<html>
<head lang="en">
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="{% static 'css/thebestwonders.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="{% static 'search.js' %}"></script>
    {% block title_block %}
    {% endblock %}
</head>
<body>
<style>
    * {
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif
    }
</style>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">
                        {% block header_info %}
                        {% endblock %}</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Account</h4>
                    <ul class="list-unstyled">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'myaccount:myaccount' %}" class="text-white">My Account</a></li>
                            <li><a href="{% url 'myaccount:logout' %}" class="text-white">Log out</a></li>
                        {% else %}
                            <li><a href="{% url 'myaccount:signup' %}" class="text-white">Sign up</a></li>
                            <li><a href="{% url 'myaccount:login' %}" class="text-white">Log in</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                     viewBox="0 0 24 24" focusable="false">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>{% block header_title %}{% endblock %}</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

{% block body_block %}

{% endblock %}

{% block foot_title %}
    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#" style="color: dodgerblue">Back to top</a>
            </p>
            <p>Group J</p>
            <p><a href="{% url 'home:index' %}" style="color: dodgerblue">Homepage</a></p>

        </div>
    </footer>
{% endblock %}
</body>
</html>

templates/search/searchpage.html
{% extends 'search/base.html' %}
{% load staticfiles %}

{% block title_block %}
    <link rel="stylesheet" href="{% static 'css/thebestwonders.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <title>search results</title>
{% endblock %}

{% block header_info %}
    This page shows the search results based on the text in the search bar.
{% endblock %}

{% block header_title %}
    search results
{% endblock %}

{% block body_block %}
    <main role="main">


        <div class="jumbotron text-center" style="padding: 5rem 0 1rem">
            <div class="search-form" style="margin: 0 auto;width: 50%;">
                <input class="form-control mr-sm-2" id="typestr" type="text"
                       style="display:inline;width: 50%;height: 3rem;" placeholder="Search" aria-label="Search"
                       onkeydown="onKeyDown()">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="display: inline"
                        onclick="searchPage()">Search
                </button>
            </div>
            <p id="hint">Hint: You can search the continents and places.</p>
        </div>

    {% if isStr %}

        <section class="jumbotron text-center" style="padding: 2rem 0 5rem">
            <div class="container">
                <h1>The search results for {{ keyword }}</h1>
            </div>
            <p>Sort by rate descending</p>
        </section>


        {% if results %}

            {#                <li>{{ page.name }}</li>#}
            <div class="row row-cols-1 row-cols-md-3 wonder-result center-block">
                {% for page in results %}
                    {% with 'images/places/'|add:page.slug|add:'.jpg' as image_static %}
                        <div class="col mb-4">
                            <a href="{% url 'category:page' page.slug %}" class="card wonder-card shadow-lg rounded">
                                <div class="img-box" style="background-image: url({% static image_static %})"></div>
                                <div class="card-body">
                                    <span style="font-family: 'Trade Winds'; font-size: 1.5rem;">{{ page.name }}</span>
                                    <span class="ml-2" style="font-family: 'Trade Winds'">{{ page.rate }}</span>
                                    <p style="font-size: 0.8rem;">{{ page.intro }}</p>
                                </div>
                            </a>
                        </div>
                    {% endwith %}
                {% endfor %}
            </div>

        {% else %}

            <h4 id="noresult">Sorry, no suitable results...</h4>

        {% endif %}

        {% else %}


    {% endif %}




    </main>

    <script type="text/javascript">

        function onKeyDown(event) {
            var e = event || window.event || arguments.callee.caller.arguments[0];
            if (e && e.keyCode == 27) { // key Esc
                document.getElementById("typestr").value = "";
            }

            if (e && e.keyCode == 13) { // key Enter
                searchPage();
            }

        }

        function searchPage() {
            var strs = document.getElementById("typestr").value.toString();
            if (strs==""){
                window.open('{% url 'search:searchhome' %}', '_self')
            }else {
                var url = '{% url 'search:searchpage' 'none' %}';
            url = url.replace('none', strs);
            window.open(url, '_self');
            }
        }

    </script>

{% endblock %}

templates/search/thebestwonders.html
{% extends 'search/base.html' %}
{% load staticfiles %}

{% block title_block %}
    <link rel="stylesheet" href="{% static 'css/thebestwonders.css' %}"/>
    <title>The best wonders</title>
{% endblock %}

{% block header_info %}
    This page lists the most popular wonders based on the rate that visitors give.
{% endblock %}

{% block header_title %}
    the most popular wonders
{% endblock %}

{% block body_block %}

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1>The most popular wonders</h1>
                <p class="lead text-muted">Here are 6 the most popular wonders.<br>They are selected by their rate and
                    updated by the time.</p>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">

                    {% for page in pages %}
                        {% with 'images/places/'|add:page.slug|add:'.jpg' as image_static %}
                            <div class="col-md-6">
                                <div class="card mb-4 shadow-sm">
                                    <img class="img-response" style="width: 100%;height: 400px" src="{% static image_static %}" alt="Picture of {{ page.slug }}"/>
                                    <div class="card-body">
                                        <p class="card-text" style="height: 190px;overflow: hidden"> {{ page.intro }}</p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.open('{% url 'category:page' page.slug %}', '_blank');">View
                                                </button>
                                            </div>
{#                                            <small class="text-muted">9 mins</small>#}
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endwith %}
                    {% endfor %}


                </div>
            </div>
        </div>

    </main>



{% endblock %}